data={
    background:'#28287B',
    white:'#fff',
    blue:'#2e74b7',
    url:'http://192.168.72.254:5000',
    about:'Lorem ipsum dolor sit amet, lacus dictum lectus eget libero aliquam, urna in, sed lacus dictum magna aliquam eget velit, faucibus nam amet integer, pellentesque facilisis integer molestie quisque massa nunc. A est quam, tempor sed in aliquam ante, hendrerit lectus diam non enim, amet dolor, parturient a. Mauris massa velit aliquam ultricies adipiscing, vitae suspendisse quisque wisi. In lacinia pulvinar id nec suspendisse, dictumst nulla litora, quam lorem tincidunt leo ipsum nunc, sed nulla praesent. Viverra pellentesque leo, vivamus nec eget vel, inceptos egestas mauris, et placerat quis neque, tempus potenti eget purus ullamcorper eum.',
    terms:'Lorem ipsum dolor sit amet, lacus dictum lectus eget libero aliquam, urna in, sed lacus dictum magna aliquam eget velit, faucibus nam amet integer, pellentesque facilisis integer molestie quisque massa nunc. A est quam, tempor sed in aliquam ante, hendrerit lectus diam non enim, amet dolor, parturient a. Mauris massa velit aliquam ultricies adipiscing, vitae suspendisse quisque wisi. In lacinia pulvinar id nec suspendisse, dictumst nulla litora, quam lorem tincidunt leo ipsum nunc, sed nulla praesent. Viverra pellentesque leo, vivamus nec eget vel, inceptos egestas mauris, et placerat quis neque, tempus potenti eget purus ullamcorper eum.',
    privacy:'Lorem ipsum dolor sit amet, lacus dictum lectus eget libero aliquam, urna in, sed lacus dictum magna aliquam eget velit, faucibus nam amet integer, pellentesque facilisis integer molestie quisque massa nunc. A est quam, tempor sed in aliquam ante, hendrerit lectus diam non enim, amet dolor, parturient a. Mauris massa velit aliquam ultricies adipiscing, vitae suspendisse quisque wisi. In lacinia pulvinar id nec suspendisse, dictumst nulla litora, quam lorem tincidunt leo ipsum nunc, sed nulla praesent. Viverra pellentesque leo, vivamus nec eget vel, inceptos egestas mauris, et placerat quis neque, tempus potenti eget purus ullamcorper eum.'
}

export default data